### ISSUE TITLE
Pictures sources not found anymore for Treasure Hunt

### ISSUE THREAD

**Issue by DanielMisch** [netmedianer-GmbH/treasure-hunt#1]
It seems, that Github moved urls so our Treasure hunt is not stuffed with pictures anymore.

**Comment by nmtoblum** [comment]
Hello @DanielMisch,

URLs should not have moved. We've verified that it's working in our environment.

If it's still not working for you, could you please check what values you have set in your TH_config list.
The values for "Path" and "BaseUrl" should look like this:
![image](https://user-images.githubusercontent.com/57751598/223183152-599d0bd7-30db-4902-bfd3-7638ae81eab6.png)

Many greetings
Tobias

**Comment by DanielMisch** [comment]
Funny, i removed the line and as expected screen stays white. i readded the line and the pictures are back online. And no i'am completely confused...

**Comment by nmtoblum** [comment]
Mhm, maybe there was a trailing space or something like that that wasn't visible, but messed up the resulting URLs. Hard to tell, but as it's working again, I think there is no need to investigate further. Let us know, if it's happening again.

Happy treasure hunting!
